import React, { useState } from 'react';
import { Alert, Button, Card, Col, Container, Form, Row } from 'react-bootstrap';
import { Eye, EyeOff, Home } from 'lucide-react';
import { Link, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

function AuthShell({ title, subtitle, children }) {
  return <div className="min-vh-100 d-grid align-items-center bg-light py-5"><Container><Row className="justify-content-center"><Col md={9} lg={6} xl={5}><div className="text-center mb-4"><Link to="/" className="text-decoration-none d-inline-flex align-items-center gap-2"><span className="sfl-brand-mark">S</span><span className="sfl-brand h4 mb-0">Supreme Fantasy League</span></Link><h1 className="h2 page-title mt-4">{title}</h1><p className="muted">{subtitle}</p></div><Card className="surface-card border-0"><Card.Body className="p-4 p-md-5">{children}</Card.Body></Card></Col></Row></Container></div>;
}

export function LoginPage() {
  const [form,setForm]=useState({email:'',password:''}); const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const { login, sessionMessage, setSessionMessage }=useAuth(); const navigate=useNavigate(); const location=useLocation(); const [searchParams]=useSearchParams();
  const requestedPlan = searchParams.get('plan') || '';
  const submit=async(e)=>{e.preventDefault();setBusy(true);setError('');try{await login(form);navigate(location.state?.from || (requestedPlan ? `/app/subscription?plan=${encodeURIComponent(requestedPlan)}` : '/app/dashboard'),{replace:true});}catch(err){setError(err.message);}finally{setBusy(false)}};
  return <AuthShell title="Welcome back" subtitle="Sign in to manage your competitions, wallet and team.">{(error||sessionMessage)&&<Alert variant="danger" onClose={()=>{setError('');setSessionMessage('')}} dismissible>{error||sessionMessage}</Alert>}<Form onSubmit={submit}><Form.Group className="mb-3"><Form.Label>Email</Form.Label><Form.Control type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Form.Group><Form.Group className="mb-4"><Form.Label>Password</Form.Label><div className="position-relative"><Form.Control type={show?'text':'password'} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" className="btn position-absolute top-50 end-0 translate-middle-y" onClick={()=>setShow(!show)} aria-label="Toggle password visibility">{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></Form.Group><Button type="submit" className="w-100" size="lg" disabled={busy}>{busy?'Signing in…':'Login'}</Button><div className="text-center mt-4 small">New here? <Link to={requestedPlan ? `/register?plan=${encodeURIComponent(requestedPlan)}` : "/register"}>Create an account</Link></div><div className="text-center mt-2 small"><Link to="/"><Home size={14}/> Home</Link></div></Form></AuthShell>;
}

export function RegisterPage() {
  const [form,setForm]=useState({fullName:'',email:'',phone:'+263',dateOfBirth:'',password:'',confirmPassword:'',ageConfirmed:false,termsAccepted:false,privacyAccepted:false});
  const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const {register}=useAuth(); const navigate=useNavigate(); const [searchParams]=useSearchParams();
  const requestedPlan = searchParams.get('plan') || '';
  const submit=async(e)=>{e.preventDefault();setBusy(true);setError('');try{await register({...form,ageConfirmed:form.ageConfirmed===true,termsAccepted:form.termsAccepted===true,privacyAccepted:form.privacyAccepted===true});navigate(requestedPlan?`/app/subscription?plan=${encodeURIComponent(requestedPlan)}`:'/app/dashboard',{replace:true});}catch(err){setError([err.message,...(err.errors||[])].join(' '));}finally{setBusy(false)}};
  return <AuthShell title="Create your account" subtitle="Adults 18+ only. Use a public fantasy manager ID later — never your fantasy password.">{error&&<Alert variant="danger">{error}</Alert>}<Form onSubmit={submit}><Row className="g-3"><Col md={6}><Form.Label>Full name</Form.Label><Form.Control required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></Col><Col md={6}><Form.Label>Email</Form.Label><Form.Control type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Col><Col md={6}><Form.Label>Zimbabwe phone</Form.Label><Form.Control required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Col><Col md={6}><Form.Label>Date of birth</Form.Label><Form.Control type="date" required value={form.dateOfBirth} onChange={e=>setForm({...form,dateOfBirth:e.target.value})}/></Col><Col md={6}><Form.Label>Password</Form.Label><div className="position-relative"><Form.Control type={show?'text':'password'} minLength={8} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" className="btn position-absolute top-50 end-0 translate-middle-y" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></Col><Col md={6}><Form.Label>Confirm password</Form.Label><Form.Control type={show?'text':'password'} required value={form.confirmPassword} onChange={e=>setForm({...form,confirmPassword:e.target.value})}/></Col><Col xs={12}><Form.Check required label="I confirm I am at least 18 years old" checked={form.ageConfirmed} onChange={e=>setForm({...form,ageConfirmed:e.target.checked})}/><Form.Check required label="I accept the Terms" checked={form.termsAccepted} onChange={e=>setForm({...form,termsAccepted:e.target.checked})}/><Form.Check required label="I accept the Privacy Policy" checked={form.privacyAccepted} onChange={e=>setForm({...form,privacyAccepted:e.target.checked})}/></Col><Col xs={12}><Button type="submit" className="w-100" size="lg" disabled={busy}>{busy?'Creating account…':'Create account'}</Button></Col></Row><div className="text-center mt-4 small">Already registered? <Link to={requestedPlan ? `/login?plan=${encodeURIComponent(requestedPlan)}` : "/login"}>Login</Link></div></Form></AuthShell>;
}
