import React, { useEffect, useState } from 'react';
import { Alert, Button, Col, Form, Row, Tab, Tabs } from 'react-bootstrap';
import { Camera, Link2, Shield, UserRound } from 'lucide-react';
import { api } from '../services/api';
import { useAuth } from '../context/AuthContext';
import PageHeader from '../components/PageHeader';
import ProfileAvatar from '../components/ProfileAvatar';
import LoadingScreen from '../components/LoadingScreen';
import ErrorState from '../components/ErrorState';
import StatusBadge from '../components/StatusBadge';

export default function ProfilePage(){
  const {setUser}=useAuth();const [data,setData]=useState(null);const [form,setForm]=useState(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [managerId,setManagerId]=useState('');
  const load=async()=>{setError('');try{const d=await api('/api/profile');setData(d);setForm({fullName:d.user.fullName,phone:d.user.phone,dateOfBirth:d.user.dateOfBirth?String(d.user.dateOfBirth).slice(0,10):'',city:d.profile.city||'',address:d.profile.address||'',country:d.user.country||'Zimbabwe',currency:d.user.currency||'USD',contactPreference:d.profile.contactPreference||'email',notificationPreferences:d.profile.notificationPreferences||{},profilePicture:d.profile.profilePicture||''});setManagerId(d.user.fplManagerId||'');}catch(e){setError(e.message)}};useEffect(()=>{load()},[]);
  const save=async(e)=>{e.preventDefault();setBusy(true);setNotice('');try{const r=await api('/api/profile',{method:'PUT',body:form});setUser(r.user);setNotice('Profile updated successfully.');await load();}catch(e){setNotice(e.message)}finally{setBusy(false)}};
  const choosePhoto=(file)=>{if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setNotice('Choose a PNG, JPEG or WebP image.');return}if(file.size>1.5*1024*1024){setNotice('Profile picture must be 1.5 MB or smaller.');return}const reader=new FileReader();reader.onload=()=>setForm({...form,profilePicture:reader.result});reader.readAsDataURL(file)};
  const linkTeam=async(e)=>{e.preventDefault();setBusy(true);setNotice('');try{await api('/api/profile/link-fantasy-team',{method:'POST',body:{managerId}});setNotice('Fantasy manager account linked.');await load();}catch(e){setNotice(e.message)}finally{setBusy(false)}};
  if(error)return <ErrorState message={error} onRetry={load}/>;if(!form)return <LoadingScreen fullScreen={false}/>;
  const pref=form.notificationPreferences;
  return <><PageHeader eyebrow="Account" title="Profile" description="Manage personal details, profile photo, connected accounts and preferences."/>{notice&&<Alert variant="info">{notice}</Alert>}<Tabs defaultActiveKey="personal" className="mb-4"><Tab eventKey="personal" title="Personal Details"><div className="surface-card p-4"><Form onSubmit={save}><Row className="g-4"><Col lg={4}><div className="text-center"><ProfileAvatar src={form.profilePicture} name={form.fullName} size="lg"/><div className="mt-3"><Button as="label" htmlFor="profile-photo" variant="outline-dark"><Camera size={16}/> Choose photo</Button><input id="profile-photo" type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>choosePhoto(e.target.files?.[0])}/>{form.profilePicture&&<Button variant="link" className="text-danger d-block mx-auto mt-2" onClick={()=>setForm({...form,profilePicture:''})}>Remove photo</Button>}</div><p className="small muted mt-3">PNG, JPEG or WebP. Maximum 1.5 MB.</p></div></Col><Col lg={8}><Row className="g-3"><Col md={6}><Form.Label>Full name</Form.Label><Form.Control value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></Col><Col md={6}><Form.Label>Email</Form.Label><Form.Control disabled value={data.user.email}/></Col><Col md={6}><Form.Label>Phone</Form.Label><Form.Control value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Col><Col md={6}><Form.Label>Date of birth</Form.Label><Form.Control type="date" value={form.dateOfBirth} onChange={e=>setForm({...form,dateOfBirth:e.target.value})}/></Col><Col md={6}><Form.Label>City</Form.Label><Form.Control value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></Col><Col md={6}><Form.Label>Country</Form.Label><Form.Control value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></Col><Col xs={12}><Form.Label>Address</Form.Label><Form.Control value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></Col><Col md={6}><Form.Label>Currency</Form.Label><Form.Select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option>USD</option></Form.Select></Col><Col md={6}><Form.Label>Preferred contact</Form.Label><Form.Select value={form.contactPreference} onChange={e=>setForm({...form,contactPreference:e.target.value})}><option value="email">Email</option><option value="sms">SMS</option><option value="phone">Phone</option></Form.Select></Col><Col xs={12}><Button type="submit" disabled={busy}>{busy?'Saving…':'Save profile'}</Button></Col></Row></Col></Row></Form></div></Tab>
  <Tab eventKey="connected" title="Connected Accounts"><div className="surface-card p-4"><div className="d-flex align-items-center gap-2 mb-3"><Link2/><h2 className="h4 mb-0">Fantasy account</h2></div><p className="muted">Only enter a public fantasy manager ID. Never enter your fantasy-platform password.</p><Form onSubmit={linkTeam}><Row className="g-2 align-items-end"><Col md={8}><Form.Label>Fantasy manager ID</Form.Label><Form.Control inputMode="numeric" pattern="[0-9]+" value={managerId} onChange={e=>setManagerId(e.target.value.replace(/\D/g,''))}/></Col><Col md={4}><Button className="w-100" type="submit" disabled={busy}>Link account</Button></Col></Row></Form>{data.user.fantasyTeamName&&<div className="soft-card p-3 mt-4"><div className="small muted">Fantasy team</div><strong>{data.user.fantasyTeamName}</strong></div>}<div className="soft-card p-3 mt-3"><div className="small muted">Payment references</div><strong>Displayed in masked form only</strong></div></div></Tab>
  <Tab eventKey="preferences" title="Preferences"><div className="surface-card p-4"><h2 className="h4">Notifications</h2>{[['emailNotifications','Email notifications'],['smsNotifications','SMS notifications'],['leagueReminders','League reminders'],['deadlineReminders','Deadline reminders'],['transactions','Transactions'],['results','Results'],['marketing','Marketing']].map(([key,label])=><Form.Check className="py-2" key={key} label={label} checked={Boolean(pref[key])} onChange={e=>setForm({...form,notificationPreferences:{...pref,[key]:e.target.checked}})}/>)}<Button className="mt-3" onClick={save} disabled={busy}>Save preferences</Button></div></Tab>
  <Tab eventKey="security" title="Security"><div className="surface-card p-4"><div className="d-flex gap-3"><Shield/><div><h2 className="h4">Account security</h2><p className="muted">Authentication uses secure HTTP-only cookies and passwords are hashed on the server. JWTs are never stored in localStorage.</p><StatusBadge status={data.user.status}/></div></div></div></Tab>
  <Tab eventKey="activity" title="Activity"><div className="surface-card p-4"><div className="d-flex gap-3"><UserRound/><div><h2 className="h4">Profile completion</h2><div className="metric-number">{data.profile.profileCompletion}%</div><p className="muted mb-0">Complete your details, link your fantasy team and add a profile picture to make your competition identity easier to recognize.</p></div></div>{data.subscription&&<div className="soft-card p-3 mt-4"><div className="small muted">Current subscription</div><strong>{data.subscription.planName}</strong> · <StatusBadge status={data.subscription.status}/></div>}</div></Tab></Tabs></>;
}
