import React from 'react';
import { Button, Container } from 'react-bootstrap';
import PublicNavbar from '../components/PublicNavbar';
import Footer from '../components/Footer';

function Shell({ eyebrow, title, children }) { return <div className="public-shell"><PublicNavbar/><main className="section-space"><Container style={{maxWidth:920}}><div className="eyebrow">{eyebrow}</div><h1 className="display-4 fw-bold mb-4">{title}</h1><div className="fs-5 lh-lg">{children}</div></Container></main><Footer/></div>; }
export function AboutPage(){return <Shell eyebrow="About" title="Competition administration should be easier to trust."><p>Supreme Fantasy League is a prototype designed around transparent competition administration: published fees, visible standings, clear result review, Zimbabwe-focused payment options, USD accounting and adult-only participation.</p><p>We do not invent claims about user numbers, licences, staff, founding dates or partnerships. The product is not affiliated with the Premier League or its fantasy game.</p></Shell>}
export function ContactPage(){return <Shell eyebrow="Contact" title="Talk to Supreme Fantasy League."><p>For prototype support, account questions, competition-rule queries or payment-status questions, use the in-app support area after signing in.</p><Button href="/login" variant="dark">Open the support area</Button></Shell>}
export function CompetitionRulesPage(){return <Shell eyebrow="Rules · Version 0.1" title="Competition Rules"><p><strong>Effective date:</strong> Prototype draft.</p><p>Rankings use the configured fantasy-data scoring source. Entry deadlines, late-entry rules, tie-breaks and prize conditions are published before entry. Users are expected to actively review and confirm their team each gameweek where the rule applies.</p><p>Three consecutive missed confirmations may make a user ineligible for applicable subscription-based prizes. Scores, rankings and historical results remain visible. Results may enter a review period before settlement. Refunds, cancellations, provider outages, disputes and suspensions are handled according to the published competition-specific rules.</p><p>Adults 18+ only. Final legal wording requires professional approval.</p></Shell>}
export function TermsPage(){return <Shell eyebrow="Legal" title="Terms"><p>This prototype demonstrates product flows and competition administration concepts. It is not production legal advice and the copy requires professional legal review before commercial launch.</p><p>Real-money functionality is disabled by default and must not be activated without the required legal, commercial, fantasy-data and payment-provider approvals.</p></Shell>}
export function PrivacyPage(){return <Shell eyebrow="Legal" title="Privacy"><p>The prototype stores account, profile, fantasy-manager, competition and transaction information needed to demonstrate the service. Passwords are hashed and authentication uses HTTP-only cookies.</p><p>Never store wallet PINs, card CVVs, full card numbers or fantasy-football passwords. Profile photos are stored as prototype image data and should move to dedicated object storage in production. Final privacy wording requires professional legal review.</p></Shell>}
